#!/bin/bash
set -e

# Buildroot variables
BINARIES_DIR="$1"
BOARD_DIR="board/swacs1d"
EFI_DIR="${BINARIES_DIR}/efi-part/EFI/BOOT"

echo "POST-IMAGE: Preparing Custom Shim + Grub Secure Boot structure..."

# 1. Locate Shim inside Buildroot's core images directory
SHIM_SRC=""
if [ -f "${BINARIES_DIR}/shim.efi" ]; then
    SHIM_SRC="${BINARIES_DIR}/shim.efi"
elif [ -f "${BINARIES_DIR}/shimx64.efi" ]; then
    SHIM_SRC="${BINARIES_DIR}/shimx64.efi"
else
    echo "ERROR: Neither shim.efi nor shimx64.efi was found in ${BINARIES_DIR}!"
    echo "Double-check your defconfig contains: BR2_TARGET_SHIM=y"
    exit 1
fi

echo "POST-IMAGE: Located valid Shim binary at: ${SHIM_SRC}"

# 1b. Locate MokManager (built alongside shim by the same upstream Makefile).
#     This is only needed for the manual/fallback MOK enrollment path (see
#     step 4 for why the primary path does not depend on it), but if it's
#     missing from the ESP, MokManager can never be invoked at all.
MOKMANAGER_SRC=""
if [ -f "${BINARIES_DIR}/mmx64.efi" ]; then
    MOKMANAGER_SRC="${BINARIES_DIR}/mmx64.efi"
elif [ -f "${BINARIES_DIR}/mm.efi" ]; then
    MOKMANAGER_SRC="${BINARIES_DIR}/mm.efi"
else
    echo "WARNING: MokManager (mmx64.efi/mm.efi) not found in ${BINARIES_DIR}. Manual MOK enrollment fallback will be unavailable."
fi

# 2. Verify Grub exists (Buildroot automatically generates it here)
ORIG_GRUB="${BINARIES_DIR}/efi-part/EFI/BOOT/bootx64.efi"
if [ ! -f "${ORIG_GRUB}" ]; then
    echo "ERROR: Original Grub binary not found at ${ORIG_GRUB}!"
    exit 1
fi

# 3. Arrange filesystem files to map standard UEFI Shim execution layouts
mkdir -p "${EFI_DIR}"

# Step A: Move the default Grub binary out of the way first, under the filename Shim expects
mv "${ORIG_GRUB}" "${EFI_DIR}/grubx64.efi"

# Step B: Copy the verified Shim source into the primary UEFI fall-through position (BOOTX64.EFI)
cp "${SHIM_SRC}" "${EFI_DIR}/BOOTX64.EFI"

# Step B2: Stage MokManager next to Shim (required if it is ever invoked)
if [ -n "$MOKMANAGER_SRC" ]; then
    cp "$MOKMANAGER_SRC" "${EFI_DIR}/mmx64.efi"
fi

# Step C: Pull custom Grub target menus over
if [ -f "${BOARD_DIR}/grub.cfg" ]; then
    cp "${BOARD_DIR}/grub.cfg" "${EFI_DIR}/grub.cfg"
else
    echo "WARNING: ${BOARD_DIR}/grub.cfg not found, keeping default Buildroot grub.cfg if present."
fi

# Step D: Deploy Shim DER Certificate for the OPTIONAL manual MOK / MokManager
# enrollment path. NOTE: this is not part of the automatic boot chain (see
# step 4) - it only matters if a technician manually enrolls it later via
# MokManager or mokutil.
if [ -f "${BOARD_DIR}/keys/shim.der" ]; then
    echo "POST-IMAGE: Deploying shim.der to EFI partition as MOK.der (manual-enrollment fallback only)..."
    cp "${BOARD_DIR}/keys/shim.der" "${EFI_DIR}/MOK.der"
else
    echo "WARNING: ${BOARD_DIR}/keys/shim.der not found! Skipping MOK storage deployment."
fi

# 4. Handle Cryptographic Code Signing Routines
#
# IMPORTANT: Buildroot's stock "shim" package builds vanilla upstream shim
# with no vendor certificate compiled in (there is no VENDOR_CERT_FILE hook
# in board/shim.mk). That means shim has no built-in trust anchor of its
# own - it can only validate the next-stage loader either:
#   a) via the firmware's own UEFI "db" (the normal LoadImage/StartImage
#      path succeeds directly, before shim's fallback logic ever runs), or
#   b) via a MOK enrolled at runtime through MokManager (requires a human
#      pressing keys at the console - not viable for headless factory
#      provisioning).
#
# Since this device is provisioned headlessly, EVERYTHING that firmware or
# shim has to validate - the shim binary itself, grub, and the kernel -
# must be signed with the SAME "db" key, because that's the only key that
# actually gets enrolled into the board's firmware (see the "Zip
# Provisioning Keys" CI step / test_factory_provision_keys.zip).
#
# The separate "shim" keypair generated by init_keys.sh is kept around only
# as an optional, manually-enrollable secondary trust anchor (via MOK.der
# above) - it must never be used to sign anything in the automatic boot
# path, or the board will fail to boot with Secure Boot enabled.
DB_KEY="${BOARD_DIR}/keys/db.key"
DB_CRT="${BOARD_DIR}/keys/db.crt"

# Always stage the kernel image to the target partition first
cp "${BINARIES_DIR}/bzImage" "${BINARIES_DIR}/efi-part/bzImage"

if command -v sbsign >/dev/null 2>&1; then
    echo "POST-IMAGE: sbsign tool discovered. Checking keys..."

    if [ -f "$DB_KEY" ] && [ -f "$DB_CRT" ]; then
        echo "POST-IMAGE: Signing BOOTX64.EFI (Shim) with DB keys (the only key enrolled in firmware)..."
        sbsign --key "$DB_KEY" --cert "$DB_CRT" --output "${EFI_DIR}/BOOTX64.EFI" "${EFI_DIR}/BOOTX64.EFI"

        if [ -n "$MOKMANAGER_SRC" ]; then
            echo "POST-IMAGE: Signing mmx64.efi (MokManager) with DB keys..."
            sbsign --key "$DB_KEY" --cert "$DB_CRT" --output "${EFI_DIR}/mmx64.efi" "${EFI_DIR}/mmx64.efi"
        fi

        echo "POST-IMAGE: Signing grubx64.efi and bzImage with DB keys..."
        sbsign --key "$DB_KEY" --cert "$DB_CRT" --output "${EFI_DIR}/grubx64.efi" "${EFI_DIR}/grubx64.efi"
        sbsign --key "$DB_KEY" --cert "$DB_CRT" --output "${BINARIES_DIR}/efi-part/bzImage" "${BINARIES_DIR}/efi-part/bzImage"
    else
        echo "POST-IMAGE: WARNING: DB keys missing. Shim, GRUB and Kernel left unsigned - Secure Boot WILL fail."
    fi

    echo "POST-IMAGE: Cryptographic validation steps completed."
else
    echo "POST-IMAGE: WARNING: sbsign tool missing! Packaging unsigned files."
fi

echo "POST-IMAGE: Formatting system image partitions via genimage wrapper..."
support/scripts/genimage.sh "$@"
